# See: https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
github:
  features:
    # Enable issue management
    issues: true

notifications:
  commits: wave@apache.org
  issues: wave@apache.org
  pullrequests: wave@apache.org

pelican:
  notify: wave@apache.org
  autobuild: preview/*
  target: asf-site
  theme: theme/apache
  whoami: main

staging:
  profile: ~
  whoami: asf-site
  autostage: preview/*
